server:
  port: 8088
  servlet:
    context-path: /api/v1
spring:
  application:
    name: furniture
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/store}
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: furniturestorewithjava@gmail.com
    password: xtsk tfiv tpno iyzi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  signer-key: WX18auptfEsbPZoT76tdwU3EPMbGKa7ien8RxT8RLqbVzI7kpxdGjmD+FsrXN460
  valid-duration: 86400
cloudinary:
  url: cloudinary://347364369644493:sBJr4Q1-QX7QQnrQ4suvM2FyCwM@dsboqyurb